### ISSUE TITLE
Not getting Verification SMS or Call

### ISSUE THREAD

**Issue by veereshpm** [WhisperSystems/TextSecure-iOS#213]
Hi Team,

I am a user from India and I am unable to enroll. Here are the details..

Network: Airtel
Device: iPhone 5s
OS Version: 8.1.3
Error: "Error Domain=com.alamofi..." (full error is not visible on the screen)

Happy to help if you need any further information.

Regards,
Veeresh

**Comment by FredericJacobs** [comment]
This project is deprecated. Check https://github.com/WhisperSystems/Signal-iOS for more information.
